export const authenticParanormalHeadlines = [
  // Declassified UAP & Military Encounters
  "Pentagon AARO releases latest report on unidentified anomalous phenomena.",
  "Whistleblower David Grusch testifies before Congress on retrieved non-human craft.",
  "Navy pilots recount Tic Tac UFO encounter off the coast of San Diego.",
  "Declassified Project Blue Book files reveal thousands of unsolved aerial mysteries.",
  "The Gimbal video: military infrared captures rotating unidentified object.",
  "Mexican Congress views alleged non-human mummies presented by researchers.",
  "Operation Highjump and the persisting rumors of Antarctic anomalies.",
  "NASA independent study team calls for better data collection on UAPs.",
  "CIA declassifies decades of UFO investigation documents under FOIA.",
  "The Phoenix Lights: thousands witness massive V-shaped craft over Arizona.",
  "Rendlesham Forest incident still unexplained after four decades.",
  "French COMETA report concludes extraterrestrial hypothesis is highly probable.",
  "Japanese Defense Minister issues protocols for UAP encounters.",
  "The Roswell crash: new witness testimonies emerge in recent documentaries.",
  "Kecksburg UFO incident: local residents still demand answers on military recovery.",
  "Shag Harbour UFO incident remains Canada's most documented aerial anomaly.",
  "O'Hare International Airport UFO sighting confirmed by multiple aviation employees.",
  "Majestic 12 documents: authentic leak or elaborate government hoax?",
  "Belgian UFO wave tracked by F-16 radar lock and multiple ground witnesses.",
  "The Ariel School phenomenon: 62 children report contact with non-human entities.",

  // Government Programs & Famous Conspiracies
  "Havana Syndrome: intelligence community divided on directed energy weapon theory.",
  "MKUltra files reveal extent of CIA mind control experiments in the 1960s.",
  "Project Stargate: the US military's two-decade exploration into remote viewing.",
  "HAARP facility in Alaska remains center of weather modification conspiracy theories.",
  "The Philadelphia Experiment: did the USS Eldridge actually achieve invisibility?",
  "Missing 411: investigator highlights bizarre clusters of national park disappearances.",
  "The Black Knight Satellite: space junk or ancient extraterrestrial monitor?",
  "Cicada 3301 puzzle remains one of the internet's most complex unsolved mysteries.",
  "Denver International Airport murals continue to spark New World Order theories.",
  "Number Stations: shortwave radio broadcasts still transmitting encrypted messages globally.",
  "The Montauk Project: alleged time travel experiments at Camp Hero radar station.",
  "Operation Paperclip: the covert recruitment of controversial scientists post-WWII.",
  "Bob Lazar's Element 115 claims re-examined following recent scientific discoveries.",
  "Hollow Earth theories persist fueled by anomalous seismic data.",
  "The Tunguska Event: was the 1908 blast a meteor or something more exotic?",
  "Area 51 base expansion captured in latest high-resolution satellite imagery.",
  "Project Sign and the origins of modern government UFO investigations.",
  "The Disclosure Project presses for release of suppressed zero-point energy tech.",
  "Men in Black phenomena documented by researchers since the early 1950s.",
  "Plumbbob nuclear tests and the urban legend of the fastest man-made object.",

  // Cryptids & Biological Anomalies
  "Patterson-Gimlin film remains un-debunked 50 years after Bigfoot recording.",
  "Point Pleasant locals report resurgence of Mothman-like aerial anomalies.",
  "Loch Ness DNA study finds significant eel presence but no prehistoric reptiles.",
  "Chupacabra sightings trace back to 1995 Puerto Rico livestock mutilations.",
  "The Beast of Gévaudan: historical records debate the nature of the 18th-century attacks.",
  "Mongolian Death Worm expeditions return from the Gobi Desert empty-handed.",
  "Yeti footprints photographed by Eric Shipton spark decades of Himalayan expeditions.",
  "The Jersey Devil legend persists in the isolated Pine Barrens of New Jersey.",
  "Fouke Monster sightings inspire classic horror documentary in rural Arkansas.",
  "Skinwalker Ranch researchers document bizarre cattle mutilations with surgical precision.",
  "Mokele-mbembe / hunters scour the Congo basin for alleged living dinosaur.",
  "Flatwoods Monster entity described by multiple witnesses in 1952 incident.",
  "The Loveland Frogman reported by police officers in Ohio encounters.",
  "Orang Pendek sightings in Sumatra backed by mysterious bipedal footprints.",
  "Dover Demon sighting in 1977 remains a localized unexplained mystery.",
  "Skunk Ape photograph from the Everglades continues to divide analysts.",
  "Thunderbird photograph legend leaves researchers searching archival newspapers.",
  "The Minnesota Iceman exhibit raises questions about hominid survival.",
  "Fresno Nightcrawler security footage stumps video forensics experts.",
  "Champ, the Lake Champlain monster, protected by local state legislation.",

  // Verified Haunted Sites & Parapsychology
  "Amityville Horror house continues to draw curiosity despite hoax claims.",
  "The Enfield Poltergeist recordings analyzed by modern audio forensics.",
  "Waverly Hills Sanatorium recognized as one of America's most active paranormal sites.",
  "Global Consciousness Project detects anomalies during major world events.",
  "The Bell Witch haunting remains the only case where a spirit allegedly caused a fatality.",
  "Ed and Lorraine Warren's occult museum relocated amidst safety concerns.",
  "The Myrtles Plantation logs hundreds of reported apparitions in historic mirrors.",
  "Poveglia Island in Italy remains strictly off-limits due to dark history.",
  "Winchester Mystery House architectural anomalies baffle structural engineers.",
  "The Stanley Hotel embraces its haunted reputation following Stephen King's stay.",
  "Trans-Allegheny Lunatic Asylum opens doors for intense overnight investigations.",
  "Electronic Voice Phenomenon (EVP) research gains traction with new audio filters.",
  "The Borley Rectory: revisiting the most haunted house in England.",
  "Aokigahara Forest magnetic anomalies disrupt compasses and GPS devices.",
  "The Villisca Axe Murder House experiences spike in unexplained audio recordings.",
  "Eastern State Penitentiary shadow figures documented on thermal imaging.",
  "The Dyatlov Pass incident: new avalanche theories fail to explain all anomalies.",
  "Mary King's Close in Edinburgh reports ongoing poltergeist activity underground.",
  "The Tower of London guards report residual hauntings on the grounds.",
  "Whaley House in San Diego maintains its title as a verified haunted location.",

  // Historical Mysteries & Artifacts
  "The Voynich Manuscript remains untranslated despite AI cryptanalysis attempts.",
  "Nazca Lines aerial survey reveals dozens of newly discovered geoglyphs.",
  "Gobekli Tepe excavations challenge established timelines of human civilization.",
  "The Antikythera Mechanism recognized as the world's first analog computer.",
  "Oak Island treasure hunters uncover bizarre lead cross in deep excavation.",
  "The Shroud of Turin radiocarbon dating results highly debated by new scientists.",
  "Yonaguni Monument off the coast of Japan: natural formation or sunken city?",
  "Piri Reis map shows Antarctica coast without ice centuries before its discovery.",
  "The Baghdad Battery suggests ancient knowledge of electrochemical energy.",
  "Stonehenge acoustic properties suggest the site was used as a massive sound chamber.",
  "The Crystal Skulls traced back to 19th-century European jewelers, despite lore.",
  "Coral Castle in Florida: how did one man move 1,100 tons of limestone?",
  "The Nazca Mummies: scientific community demands independent genetic testing.",
  "Puma Punku stone structures display precision drilling matching modern tools.",
  "The Georgia Guidestones destroyed by explosives in unsolved local mystery.",
  "Mount Shasta continues to be a hotspot for alleged Lemurian encounters.",
  "The Taos Hum remains a persistent auditory anomaly for New Mexico residents.",
  "Bimini Road underwater rock formation fuels ongoing Atlantis speculation.",
  "The Dropa Stones translated to tell a tale of ancient extraterrestrial crash.",
  "Moai statues of Easter Island found to have extensive subterranean bodies."
];
